server:
  port: 8081
  servlet:
    #    context-path: /resource-server
    context-path: /v1/aes
  tomcat:
    max-swallow-size: -1
file:
  upload-dir: src/main/resources/static/uploadedDocuments
  download-dir: src/main/resources/static/signedDocuments

####### resource server configuration properties
spring:
  profiles:
    active: local
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    username: tbd
    password: tbd
    url: jdbc:mysql://localhost:3306/aes
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_SERVER:http://localhost:8083}/auth/realms/aes
          jwk-set-uri: ${OAUTH2_SERVER:http://localhost:8083}/auth/realms/aes/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    username: tbd
    password: tbd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
keystore:
  store-pass: tbd
  key-pass: tbd

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    oauth:
      clientId: aes-app
      clientSecret: fz4s7y2TY4dMgotxUDZdYqXpzyCpWOub
    try-it-out-enabled: false
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
  oAuthFlow:
    authorizationUrl: ${OAUTH2_SERVER:http://localhost:8083}/auth/realms/aes/protocol/openid-connect/auth
    tokenUrl: ${OAUTH2_SERVER:http://localhost:8083}/auth/realms/aes/protocol/openid-connect/token
  default-produces-media-type: application/json
